language: node_js
node_js:
  - '10'
dist: trusty
sudo: required

env:
  global:
    - REPO_NAME="https://GT_TOKEN@github.com/alexander-lloyd/angular-monorepo.git"
    - GITHUB_NAME="The Alex Bot"
    - MESSAGE="Deployed Application"
    - GITHUB_EMAIL="deploy@botbot.com"

before_script:
  - curl -s https://codecov.io/bash > .codecov
  - chmod +x .codecov

script:
  - yarn ng build --prod --base-href "https://alexander-lloyd.github.io/angular-monorepo/"
  - yarn test --code-coverage
  - yarn lint
  - yarn e2e
  - ./.codecov -f coverage/**/*.json

after_success:
  - yarn deploy \
      --repo="$REPO_NAME" \
      --message="$MESSAGE" \
      --name="$GITHUB_NAME" \
      --email="$GITHUB_EMAIL" \
      --dir="dist/apps/todo-app" \
      --no-dotfiles
